### ISSUE TITLE
Error is not processed by nest logger when wrong token is passed

### ISSUE THREAD

**Issue by Maxttier** [nksmnf/nestjs-telegraf#1260]
Generate error what is not handled by nest logger if wrong token is passed for example https://github.com/robot-mafia/nestjs-telegraf/blob/194419dc799f0872fcf4000a5e1266c462dac8c7/lib/utils/create-bot-factory.util.ts#L16

```
const bot = new Telegraf<any>(options.token, options.options);

  bot.use(...(options.middlewares ?? []));
  bot.catch((err, ctx) =>
    Logger.error(err, `Telegraf: ${ctx.botInfo.username}`), // that not help
  );

  if (options.launchOptions !== false) {
    bot.launch(options.launchOptions);  // here thrown error
  }
```

Can catch it with

```
if (options.launchOptions !== false) {
    bot
      .launch(options.launchOptions)
      .catch((err) => Logger.error(err.stack, 'Telegraf')); // that
  }
```

**Comment by Maxttier** [comment]
With that change will be

```
[NestApp] 10000  - 12/08/2024, 1:00:00 PM   ERROR [Telegraf] Error: 404: Not Found
    at new TelegramError (/home/projects/app/node_modules/telegraf/lib/core/network/error.js:6:9)
    at <anonymous> (/home/projects/app/node_modules/telegraf/lib/core/network/client.js:315:31)
    at processTicksAndRejections (native:7:39)
```

**Comment by ramincsy** [comment]
Agreed — an unhandled launch() rejection (e.g. bad token) bypassing Nest's Logger makes startup failures look like a hard crash.

I see #1348 already sketches the catch-based fix. I can review/test it against current main, including the create-bot-factory path and Nest Logger output. Related: I'm also looking at the broken docs links in #1279 if you want both in one docs/ops pass.
