### ISSUE TITLE
@Start and events not fired

### ISSUE THREAD

**Issue by MyWay** [nksmnf/nestjs-telegraf#322]
Hello, I'm trying the small piece of code on the README, but events are never fired. I'm decorating the class with @Update(), the method for the /start command with @Start() and so on for commands with @Command(). The constructor of that class is correctly fired and I see no errors. Any idea?

```javascript
import { Update, Start, Help, Command, Ctx, Hears } from 'nestjs-telegraf';
import { Context } from 'telegraf';

import { AppService } from './app.service';

@Update()
export class AppUpdate {
  constructor(private readonly appService: AppService) {
    console.log('constructor fired');
  }

  @Start()
  onStart(): string {
    console.log('onStart() fired');
    return "Welcome!";
  }
}
```

**Comment by evilsprut** [comment]
I tried your example and it works for me. Tell me, `AppUpdate` class is included as a provider in the `AppModule`? `telegraf` and `nestjs-telegraf` version?

**Comment by MyWay** [comment]
Yes, AppUpdate is included:
```
providers: [AppUpdate, AppService],
```
`"telegraf": "^4.2.1"` and `"nestjs-telegraf": "^2.2.2"`

**Comment by MyWay** [comment]
I have cloned your repository, set my bot token and tried your sample. It's not working for me, but at least I'm getting an error at start, there:
```
[Nest] 76278   - 10/03/2021, 20:51:41   [ExceptionHandler] 404: Not Found +230ms
Error: 404: Not Found
    at Telegram.callApi (/test/nestjs-telegraf/sample/01-complete-app/node_modules/telegraf/lib/core/network/client.js:259:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Telegraf.launch (/test/nestjs-telegraf/sample/01-complete-app/node_modules/telegraf/lib/telegraf.js:95:78)
    at async Object.createBotFactory (/test/nestjs-telegraf/sample/01-complete-app/node_modules/nestjs-telegraf/dist/utils/create-bot-factory.util.js:10:9)
    at async InstanceWrapper.useFactory [as metatype] (/test/nestjs-telegraf/sample/01-complete-app/node_modules/nestjs-telegraf/dist/telegraf-core.module.js:64:44)
    at async Injector.instantiateClass (/test/nestjs-telegraf/sample/01-complete-app/node_modules/@nestjs/core/injector/injector.js:290:37)
    at async callback (/test/nestjs-telegraf/sample/01-complete-app/node_modules/@nestjs/core/injector/injector.js:42:30)
    at async Injector.resolveConstructorParams (/test/nestjs-telegraf/sample/01-complete-app/node_modules/@nestjs/core/injector/injector.js:114:24)
    at async Injector.loadInstance (/test/nestjs-telegraf/sample/01-complete-app/node_modules/@nestjs/core/injector/injector.js:46:9)
    at async Injector.loadProvider (/test/nestjs-telegraf/sample/01-complete-app/node_modules/@nestjs/core/injector/injector.js:68:9)
```
Which seems related to Telegraf library/API. Any idea why this is happening?

**Comment by evilsprut** [comment]
@MyWay looks like a not `nestjs-telegraf` problem. Here's what I can suggest:
1. Try to run `telegraf` without `nestjs-telegraf` for exclue `nestjs-telegraf` specific problems.
2. Try to debug `telegraf`, simply run `export DEBUG='telegraf:*'` command before starting project with `nestjs-telegraf` or `telegraf`.

**Comment by evilsprut** [comment]
Also, i see `at Telegram.callApi (/test/nestjs-telegraf/sample/01-complete-app/node_modules/telegraf/lib/core/network/client.js:259:19)` error. It seems to me that you just don't have access to the Telegram Bot API, maybe it's blocked by your ISP or something like that.

**Comment by MyWay** [comment]
Maybe something with my newly generated bot token. I'll wait tomorrow, as it seems now your sample is working, while mine still not. Thanks for the help.

**Comment by MyWay** [comment]
In the end the problem was both with the token initially not working and for `await app.listen(3000);` inside `main.ts`, which I had removed (I thought I could remove it).
